### ISSUE TITLE
dns issue?

### ISSUE THREAD

**Issue by ofZach** [azuremous/ofSiteKR#5]
I am getting this email - 

안녕하세요. DNSEver 입니다.

openframeworks.kr의 도메인네임서비스의 이용요금을 납부하지 않아서 서비스가 중지되었습니다.

미납 요금	1,000포인트

스탠다드 DNS 서비스는 후불제이며, 포인트를 충전해두시면 청구일에 포인트가 자동차감되어 결제됩니다.
서비스를 계속 이용하려면, 포인트를 충전해주시기 바랍니다. 
미납요금 납부시 10분이내로 서비스 정지가 해제됩니다.
DNS서비스는 월단위 요금제이므로, 포인트 충전을 여유있게 해두세요.
포인트충전 바로가기: https://kr.dnsever.com/charge.html?instantKey=y4fhNGgB4oy7foGhoEa9oOPmuN5RxRmkverGhk4qdRgFNcOSm8FeIxcJMBUPCPmgAOqMLoiWMiNlpz4V2%2Fa02y8bTHdBxPbKrWeubkxHBG0KIWtQ%2FNYXoldC0BoYWG2NnbApdfk0KdGCypgyS2j9UgNeHsmKs0V7OcDN76465XM%3D
DNSEver는 안정적인 DNS 서비스를 제공하기 위하여 최선을 다합니다.
감사합니다. 

웹기반 DNS서비스 www.DNSEver.com

**Comment by azuremous** [comment]
oops~I'll fix for this. Thanks for your commented.
